/* eslint-disable */
// This base model was auto-generated by export_app
// PLEASE DO NOT EDIT
// you can make changes in app/models/accounting/invoice.js
// or regenerate this file by running
// `./manage.py export accounting/invoices`

import Model from 'ember-data/model';

import attr from 'ember-data/attr';


import { belongsTo, hasMany } from 'ember-data/relationships';


export default Model.extend({
  
    date: attr('nullable'),
  
    invoice_type: attr('string'),
  
    state: attr('string'),
  
    __str__: attr('string'),
  
  
    lines: hasMany('accounting/invoiceline', {
      async: true,
      inverse: 'invoice',
    }),
  
    related_party: belongsTo('crm/company', {
      async: true,
      inverse: 'invoices',
    }),
  
});
