# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('is_client', models.BooleanField(default=True)),
                ('is_supplier', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('long_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='crm.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism_type', models.CharField(choices=[('phone', 'Fixed phone'), ('mobile', 'Mobile phone'), ('email', 'E-Mail'), ('other', 'Other')], max_length=6)),
                ('value', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactmechanisms', to='crm.Contact')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('companies', models.ManyToManyField(blank=True, related_name='segments', to='crm.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='default_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.Contact'),
        ),
    ]
